project_id = "lqtjwcphidbwiwrnqbac"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.polar-webhook]
verify_jwt = false
