/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as NuevaSucursalRouteImport } from './routes/nueva-sucursal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardAdminRouteImport } from './routes/dashboard-admin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as TSlugReportesRouteImport } from './routes/t.$slug.reportes'
import { Route as TSlugPersonalRouteImport } from './routes/t.$slug.personal'
import { Route as TSlugOrdenesRouteImport } from './routes/t.$slug.ordenes'
import { Route as TSlugNuevaOrdenRouteImport } from './routes/t.$slug.nueva-orden'
import { Route as TSlugLoginRouteImport } from './routes/t.$slug.login'
import { Route as TSlugGastosRouteImport } from './routes/t.$slug.gastos'
import { Route as TSlugEntregasRouteImport } from './routes/t.$slug.entregas'
import { Route as TSlugConfiguracionRouteImport } from './routes/t.$slug.configuracion'
import { Route as TSlugClientesRouteImport } from './routes/t.$slug.clientes'
import { Route as TSlugCatalogoRouteImport } from './routes/t.$slug.catalogo'
import { Route as TSlugCajaRouteImport } from './routes/t.$slug.caja'

const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaSucursalRoute = NuevaSucursalRouteImport.update({
  id: '/nueva-sucursal',
  path: '/nueva-sucursal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard-admin',
  path: '/dashboard-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugReportesRoute = TSlugReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugPersonalRoute = TSlugPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugOrdenesRoute = TSlugOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugNuevaOrdenRoute = TSlugNuevaOrdenRouteImport.update({
  id: '/nueva-orden',
  path: '/nueva-orden',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugLoginRoute = TSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugGastosRoute = TSlugGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugEntregasRoute = TSlugEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugConfiguracionRoute = TSlugConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugClientesRoute = TSlugClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCatalogoRoute = TSlugCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCajaRoute = TSlugCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => TSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/login': typeof LoginRoute
  '/nueva-sucursal': typeof NuevaSucursalRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/t/$slug/caja': typeof TSlugCajaRoute
  '/t/$slug/catalogo': typeof TSlugCatalogoRoute
  '/t/$slug/clientes': typeof TSlugClientesRoute
  '/t/$slug/configuracion': typeof TSlugConfiguracionRoute
  '/t/$slug/entregas': typeof TSlugEntregasRoute
  '/t/$slug/gastos': typeof TSlugGastosRoute
  '/t/$slug/login': typeof TSlugLoginRoute
  '/t/$slug/nueva-orden': typeof TSlugNuevaOrdenRoute
  '/t/$slug/ordenes': typeof TSlugOrdenesRoute
  '/t/$slug/personal': typeof TSlugPersonalRoute
  '/t/$slug/reportes': typeof TSlugReportesRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/login': typeof LoginRoute
  '/nueva-sucursal': typeof NuevaSucursalRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/t/$slug/caja': typeof TSlugCajaRoute
  '/t/$slug/catalogo': typeof TSlugCatalogoRoute
  '/t/$slug/clientes': typeof TSlugClientesRoute
  '/t/$slug/configuracion': typeof TSlugConfiguracionRoute
  '/t/$slug/entregas': typeof TSlugEntregasRoute
  '/t/$slug/gastos': typeof TSlugGastosRoute
  '/t/$slug/login': typeof TSlugLoginRoute
  '/t/$slug/nueva-orden': typeof TSlugNuevaOrdenRoute
  '/t/$slug/ordenes': typeof TSlugOrdenesRoute
  '/t/$slug/personal': typeof TSlugPersonalRoute
  '/t/$slug/reportes': typeof TSlugReportesRoute
  '/t/$slug': typeof TSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/login': typeof LoginRoute
  '/nueva-sucursal': typeof NuevaSucursalRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/t/$slug/caja': typeof TSlugCajaRoute
  '/t/$slug/catalogo': typeof TSlugCatalogoRoute
  '/t/$slug/clientes': typeof TSlugClientesRoute
  '/t/$slug/configuracion': typeof TSlugConfiguracionRoute
  '/t/$slug/entregas': typeof TSlugEntregasRoute
  '/t/$slug/gastos': typeof TSlugGastosRoute
  '/t/$slug/login': typeof TSlugLoginRoute
  '/t/$slug/nueva-orden': typeof TSlugNuevaOrdenRoute
  '/t/$slug/ordenes': typeof TSlugOrdenesRoute
  '/t/$slug/personal': typeof TSlugPersonalRoute
  '/t/$slug/reportes': typeof TSlugReportesRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard-admin'
    | '/login'
    | '/nueva-sucursal'
    | '/recuperar'
    | '/registro'
    | '/restablecer-contrasena'
    | '/t/$slug'
    | '/t/$slug/caja'
    | '/t/$slug/catalogo'
    | '/t/$slug/clientes'
    | '/t/$slug/configuracion'
    | '/t/$slug/entregas'
    | '/t/$slug/gastos'
    | '/t/$slug/login'
    | '/t/$slug/nueva-orden'
    | '/t/$slug/ordenes'
    | '/t/$slug/personal'
    | '/t/$slug/reportes'
    | '/t/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard-admin'
    | '/login'
    | '/nueva-sucursal'
    | '/recuperar'
    | '/registro'
    | '/restablecer-contrasena'
    | '/t/$slug/caja'
    | '/t/$slug/catalogo'
    | '/t/$slug/clientes'
    | '/t/$slug/configuracion'
    | '/t/$slug/entregas'
    | '/t/$slug/gastos'
    | '/t/$slug/login'
    | '/t/$slug/nueva-orden'
    | '/t/$slug/ordenes'
    | '/t/$slug/personal'
    | '/t/$slug/reportes'
    | '/t/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard-admin'
    | '/login'
    | '/nueva-sucursal'
    | '/recuperar'
    | '/registro'
    | '/restablecer-contrasena'
    | '/t/$slug'
    | '/t/$slug/caja'
    | '/t/$slug/catalogo'
    | '/t/$slug/clientes'
    | '/t/$slug/configuracion'
    | '/t/$slug/entregas'
    | '/t/$slug/gastos'
    | '/t/$slug/login'
    | '/t/$slug/nueva-orden'
    | '/t/$slug/ordenes'
    | '/t/$slug/personal'
    | '/t/$slug/reportes'
    | '/t/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  LoginRoute: typeof LoginRoute
  NuevaSucursalRoute: typeof NuevaSucursalRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  TSlugRoute: typeof TSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-sucursal': {
      id: '/nueva-sucursal'
      path: '/nueva-sucursal'
      fullPath: '/nueva-sucursal'
      preLoaderRoute: typeof NuevaSucursalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-admin': {
      id: '/dashboard-admin'
      path: '/dashboard-admin'
      fullPath: '/dashboard-admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/reportes': {
      id: '/t/$slug/reportes'
      path: '/reportes'
      fullPath: '/t/$slug/reportes'
      preLoaderRoute: typeof TSlugReportesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/personal': {
      id: '/t/$slug/personal'
      path: '/personal'
      fullPath: '/t/$slug/personal'
      preLoaderRoute: typeof TSlugPersonalRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/ordenes': {
      id: '/t/$slug/ordenes'
      path: '/ordenes'
      fullPath: '/t/$slug/ordenes'
      preLoaderRoute: typeof TSlugOrdenesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/nueva-orden': {
      id: '/t/$slug/nueva-orden'
      path: '/nueva-orden'
      fullPath: '/t/$slug/nueva-orden'
      preLoaderRoute: typeof TSlugNuevaOrdenRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/login': {
      id: '/t/$slug/login'
      path: '/login'
      fullPath: '/t/$slug/login'
      preLoaderRoute: typeof TSlugLoginRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/gastos': {
      id: '/t/$slug/gastos'
      path: '/gastos'
      fullPath: '/t/$slug/gastos'
      preLoaderRoute: typeof TSlugGastosRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/entregas': {
      id: '/t/$slug/entregas'
      path: '/entregas'
      fullPath: '/t/$slug/entregas'
      preLoaderRoute: typeof TSlugEntregasRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/configuracion': {
      id: '/t/$slug/configuracion'
      path: '/configuracion'
      fullPath: '/t/$slug/configuracion'
      preLoaderRoute: typeof TSlugConfiguracionRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/clientes': {
      id: '/t/$slug/clientes'
      path: '/clientes'
      fullPath: '/t/$slug/clientes'
      preLoaderRoute: typeof TSlugClientesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/catalogo': {
      id: '/t/$slug/catalogo'
      path: '/catalogo'
      fullPath: '/t/$slug/catalogo'
      preLoaderRoute: typeof TSlugCatalogoRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/caja': {
      id: '/t/$slug/caja'
      path: '/caja'
      fullPath: '/t/$slug/caja'
      preLoaderRoute: typeof TSlugCajaRouteImport
      parentRoute: typeof TSlugRoute
    }
  }
}

interface TSlugRouteChildren {
  TSlugCajaRoute: typeof TSlugCajaRoute
  TSlugCatalogoRoute: typeof TSlugCatalogoRoute
  TSlugClientesRoute: typeof TSlugClientesRoute
  TSlugConfiguracionRoute: typeof TSlugConfiguracionRoute
  TSlugEntregasRoute: typeof TSlugEntregasRoute
  TSlugGastosRoute: typeof TSlugGastosRoute
  TSlugLoginRoute: typeof TSlugLoginRoute
  TSlugNuevaOrdenRoute: typeof TSlugNuevaOrdenRoute
  TSlugOrdenesRoute: typeof TSlugOrdenesRoute
  TSlugPersonalRoute: typeof TSlugPersonalRoute
  TSlugReportesRoute: typeof TSlugReportesRoute
  TSlugIndexRoute: typeof TSlugIndexRoute
}

const TSlugRouteChildren: TSlugRouteChildren = {
  TSlugCajaRoute: TSlugCajaRoute,
  TSlugCatalogoRoute: TSlugCatalogoRoute,
  TSlugClientesRoute: TSlugClientesRoute,
  TSlugConfiguracionRoute: TSlugConfiguracionRoute,
  TSlugEntregasRoute: TSlugEntregasRoute,
  TSlugGastosRoute: TSlugGastosRoute,
  TSlugLoginRoute: TSlugLoginRoute,
  TSlugNuevaOrdenRoute: TSlugNuevaOrdenRoute,
  TSlugOrdenesRoute: TSlugOrdenesRoute,
  TSlugPersonalRoute: TSlugPersonalRoute,
  TSlugReportesRoute: TSlugReportesRoute,
  TSlugIndexRoute: TSlugIndexRoute,
}

const TSlugRouteWithChildren = TSlugRoute._addFileChildren(TSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  LoginRoute: LoginRoute,
  NuevaSucursalRoute: NuevaSucursalRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  TSlugRoute: TSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
